### ISSUE TITLE
Add a DOI for citation?

### ISSUE THREAD

**Issue by dhhagan** [darothen/py-mie#6]
Last issue for a bit (most likely). I am probably going to use some calculations performed using this library in a manuscript. Would you be interested in adding a DOI to the repo so it can easily be cited/credited?

I usually use zenodo for this (for github repo's): https://guides.github.com/activities/citable-code/

**Comment by darothen** [comment]
Done! Here's a link to the [official DOI](https://doi.org/10.5281/zenodo.192510). I've updated the [README](https://github.com/darothen/py-mie/blob/master/README.md) to reflect this, and added some citation instructions. Please do cite the DOI for the wrapper library, but also be sure to cite either Toon and Ackerman (1981) or Bohren and Huffman (1983) depending on which code you used!

Closed by 9e16c61
